import { Open_Sans } from 'next/font/google';

import SWRConfigContext from '@/context/SWRConfigContext';
import AuthContext from '@/context/AuthContext';
import Header from '@/components/Header';

import './globals.css';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
        <AuthContext>
          <Header />
          <main>
            <SWRConfigContext>{children}</SWRConfigContext>
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
